// Everything the site says about the projects lives here.
// `graph` = the white words that get connected on the project page,
// `field` = the grey words floating behind them.
const PROJECTS = [
  {
    slug: "analyst-agent",
    name: "analyst-agent",
    title: "ANALYST-AGENT",
    year: 2026,
    caption: "SELF-INITIATED · PYTHON & CLAUDE CODE",
    figure: "≈ 2 MIN PER ONE-PAGER",
    text: "Give it a company name and it builds an investment one-pager: financials from Yahoo Finance, growth and margins, a quick screening DCF and a sourced thesis, rendered as a PPTX slide. Scripts do everything with a number in it, so the figures are the same every run. A Claude agent does the research and checks the output.",
    graph: ["ticker", "fetch", "margins", "DCF", "thesis", "sources", "render", "one-pager", "judgement", "reproducible"],
    field: ["Getinge", "Ambea", "IFRS 16", "free cash flow", "WACC", "terminal growth", "Yahoo Finance", "python-pptx", "skill", "agent", "research", "risk", "screening", "medtech", "Nordic", "revenue", "EBITDA", "valuation", "deck", "QA", "sourcing", "web search", "lease", "heuristic", "chart", "table"],
    media: [{ src: "assets/analyst-getinge.png", alt: "Generated one-pager for Getinge AB", invert: true }],
    link: "https://github.com/subodhbgwt/analyst-agent",
  },
  {
    slug: "research-harness",
    name: "Research harness",
    title: "RESEARCH HARNESS",
    year: 2026,
    caption: "SELF-INITIATED · PREDICTION MARKETS",
    figure: "4 LOOK-AHEAD BUGS CAUGHT",
    text: "A Python framework for testing prediction-market strategies before any money goes in. It rejected four strategies on fees, tax and execution. Along the way I found four look-ahead bugs, one of which had pushed a t-statistic from 0.03 to 1.77, and killed a z = 3.5 result with a pre-registered check: it was selection, not mispricing. Checking the fee model against on-chain data showed the old one understated taker costs by around 70% of a typical arbitrage edge.",
    graph: ["hypothesis", "backtest", "look-ahead", "fees", "tax", "execution", "pre-registered", "selection", "rejected", "honest"],
    field: ["t-statistic", "z = 3.5", "on-chain", "taker fee", "Polymarket", "price bucket", "Swedish tax", "robustness", "power", "sample size", "spread", "slippage", "arbitrage", "weather", "market making", "bias", "overfitting", "54 modules", "106 tests", "1,284 observations", "edge", "noise", "variance", "regime"],
    media: [],
    link: null,
  },
  {
    slug: "code-league",
    name: "Florent Code League",
    title: "FLORENT CODE LEAGUE",
    year: 2026,
    caption: "ANTHROPIC × FLORENT · ATTACKING STRATEGY",
    figure: "PEAK #1 · 13TH OF ~130",
    text: "A four-week competition for autonomous AI agents, run by Anthropic and Florent. I owned our team's attacking strategy. We reached first place on the live leaderboard, then finished 13th after we stopped iterating in the final week. The lesson stuck: a lead on an adversarial leaderboard is a decaying asset.",
    graph: ["agent", "sandbox", "attack", "leaderboard", "first place", "iterate", "adversarial", "team", "decay", "13th"],
    field: ["Anthropic", "Florent", "autonomous", "four weeks", "strategy", "opponents", "replay", "eval", "champion", "challenger", "latency", "cost", "prompt", "tooling", "logs", "130 teams", "defence", "meta", "patch", "rollout"],
    media: [],
    link: null,
  },
  {
    slug: "tradingbot",
    name: "TradingBot",
    title: "TRADINGBOT",
    year: 2026,
    caption: "SELF-INITIATED · SYSTEMATIC TRADING",
    figure: "MAX DRAWDOWN −55% → −27%",
    text: "A trend-following bot for SPY: an SMA 20/130 crossover, an ADX filter so it only trades in a clear trend, and a 2x ATR exit. It trades on Alpaca's paper API. Backtested on 21 years of daily data, it roughly halved volatility and drawdown compared with buy and hold, at the cost of a lower total return.",
    graph: ["SPY", "SMA 20/130", "ADX > 25", "2x ATR", "long / flat", "next bar", "drawdown", "volatility", "Sharpe", "paper trading"],
    field: ["Alpaca", "21 years", "138 trades", "trend", "crossover", "regime", "buy and hold", "equity curve", "log scale", "win rate", "holding period", "Sortino", "CAGR", "minute bars", "market order", "stop", "signal", "backtest", "pandas", "yfinance"],
    media: [{ src: "assets/tradingbot-equity.png", alt: "Equity curve of the strategy against buy and hold", invert: true }],
    link: "https://github.com/subodhbgwt/TradingBot",
  },
  {
    slug: "monte-carlo",
    name: "Monte Carlo pricer",
    title: "MONTE CARLO PRICER",
    year: 2026,
    caption: "SELF-INITIATED · OPTIONS PRICING",
    figure: "−62% STANDARD ERROR",
    text: "Prices European and Asian options by simulating geometric Brownian motion, checked against the closed-form Black-Scholes price. A control variate on the discounted stock price cut the standard error by about 62%. Antithetic variates barely helped on an at-the-money call, and the README explains why.",
    graph: ["GBM", "Black-Scholes", "European", "Asian", "antithetic", "control variate", "standard error", "convergence", "martingale", "95% CI"],
    field: ["risk-neutral", "drift", "volatility", "strike", "payoff", "discount", "paths", "252 steps", "seed", "variance", "Longstaff-Schwartz", "Heston", "Sobol", "NumPy", "Hull", "closed form", "estimator", "bias", "noise", "simulation"],
    media: [{ src: "assets/montecarlo-convergence.png", alt: "Convergence of plain and variance-reduced Monte Carlo estimates", invert: true }],
    link: "https://github.com/subodhbgwt/MonteCarloSim",
  },
  {
    slug: "internship-radar",
    name: "Internship radar",
    title: "INTERNSHIP RADAR",
    year: 2026,
    caption: "SELF-INITIATED · AUTOMATION",
    figure: "RUNS EVERY MORNING",
    text: "A bot that reads company job boards every morning and messages me on Telegram when a student role in Europe looks worth applying to. Everything it finds also goes into an Excel tracker. I started from an open-source alerter and rewrote the filters for my own search.",
    graph: ["scrape", "filter", "location", "track", "student role", "dedupe", "Telegram", "tracker", "schedule", "catch up"],
    field: ["Greenhouse", "Lever", "Ashby", "Workday", "JobSpy", "Jane Street", "IMC", "SIG", "spring week", "off-cycle", "Stockholm", "London", "Zurich", "Amsterdam", "Excel", "state.json", "asyncio", "08:00", "Monday", "fork", "tests"],
    media: [],
    link: "https://github.com/subodhbgwt/arcyinternalerter",
  },
  {
    slug: "bengt-dahlgren",
    name: "Dashboard for Bengt Dahlgren",
    title: "BENGT DAHLGREN",
    year: 2026,
    caption: "KTH INDUSTRY PROJECT · CO-LEAD",
    figure: "8-PERSON TEAM",
    text: "A KTH industry project: a Dash dashboard built on top of the client's algorithmic solver. I co-led the team of eight, ran planning and client contact with five on-site meetings and written updates every two weeks, and wrote Dash code too. The code was ready early. Most of the work was understanding what the client needed, so they would keep using it after we left.",
    graph: ["client", "requirements", "solver", "dashboard", "planning", "on-site", "updates", "adoption", "team", "handover"],
    field: ["Dash", "Plotly", "Python", "KPI", "sprint", "scrum", "Bengt Dahlgren", "KTH", "six months", "eight people", "feedback", "scope", "deadline", "users", "engineers", "translation"],
    media: [],
    link: null,
  },
  {
    slug: "fpga",
    name: "Image processing on FPGA",
    title: "IMAGE PROCESSING ON FPGA",
    year: 2025,
    caption: "KTH IS1500 · COURSE PROJECT",
    figure: "RISC-V · C · ASSEMBLY",
    text: "Convolution filters (blur, sharpen, edge detection and emboss) running on a RISC-V soft core on a DE10-Lite board. Two filters can be chained, the switches pick them, and the result shows on a VGA monitor while performance counters measure the cycles each convolution takes.",
    graph: ["convolution", "kernel", "Gaussian", "edge", "emboss", "chain", "switches", "VGA", "cycles", "RISC-V"],
    field: ["DE10-Lite", "320x240", "grayscale", "UART", "upload", "download", "clamp", "normalise", "bias", "LED9", "KEY1", "Makefile", "boot.S", "framebuffer", "pixels", "C", "assembly"],
    media: [
      { src: "assets/fpga-input.png", alt: "Input image" },
      { src: "assets/fpga-output.png", alt: "Filtered output image" },
    ],
    link: "https://github.com/subodhbgwt/ImageProcessor",
  },
  {
    slug: "social-graph-db",
    name: "Social-graph database",
    title: "SOCIAL-GRAPH DATABASE",
    year: 2025,
    caption: "KTH COURSE PROJECT · DATABASES",
    figure: "POSTGRESQL · DOCKER",
    text: "A normalised PostgreSQL schema for a social media platform, run in Docker and stress-tested with bulk inserts. Every query is parameterised to protect against SQL injection.",
    graph: ["schema", "normalised", "users", "follows", "posts", "indexes", "bulk insert", "parameterised", "Docker", "injection"],
    field: ["PostgreSQL", "foreign key", "join", "query plan", "constraints", "triggers", "seed data", "load test", "container", "SQL", "transactions", "migrations"],
    media: [],
    link: null,
  },
];
